sonar.projectKey=Test_01
sonar.projectName=SpringBootUIDemoProject
sonar.projectVersion=1.0

# Only main code here
sonar.sources=src/main/java

# Explicitly mark test code
sonar.tests=src/test/java

# Compiled bytecode
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions (no overlap with tests)
sonar.exclusions=**/target/**, **/generated/**

# Coverage report (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
